import {appImages} from '../../../globals/utilities/assets';

export const Maintabs = [
  {
    title: 'Photo',
    icon: appImages.search1,
    subtitle: 'Photographers',
  },
  {
    title: 'Video',
    icon: appImages.search2,
    subtitle: 'Videographers',
  },
  {
    title: 'Studio',
    icon: appImages.search3,
    subtitle: 'Studios',
  },
  {
    title: 'Models',
    icon: appImages.search4,
    subtitle: 'Models',
  },
  //   {
  //     title: 'Artist',
  //     icon: appImages.search5,
  //     subtitle: 'Artists',
  //   },
];
export const Searchtabs = [
  {
    title: 'Photo',
    icon: appImages.photo1,
    subtitle: 'Photographers',
  },
  {
    title: 'Video',
    icon: appImages.video1,
    subtitle: 'Videographers',
  },
  {
    title: 'Studio',
    icon: appImages.fullStudio,
    subtitle: 'Studios',
  },
  {
    title: 'Models',
    icon: appImages.model1,
    subtitle: 'Models',
  },
  //   {
  //     title: 'Artist',
  //     icon: appImages.search5,
  //     subtitle: 'Artists',
  //   },
];

export const Models = [
  {
    title: 'Explore nearby',
    details: [
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Male',
        age: '30',
        rating: 4,
        photo: appImages.user1,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Male',
        age: '30',
        rating: 4,
        photo: appImages.user2,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Female',
        age: '25',
        rating: 3,
        photo: appImages.user3,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Male',
        age: '30',
        rating: 4,
        photo: appImages.user4,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Male',
        age: '30',
        rating: 4,
        photo: appImages.user5,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Female',
        age: '25',
        rating: 3,
        photo: appImages.user6,
      },
    ],
  },
  {
    title: 'Models',
    details: [
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Male',
        age: '30',
        rating: 4,
        photo: appImages.user1,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Male',
        age: '30',
        rating: 4,
        photo: appImages.user2,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Female',
        age: '25',
        rating: 3,
        photo: appImages.user3,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Male',
        age: '30',
        rating: 4,
        photo: appImages.user4,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Male',
        age: '30',
        rating: 4,
        photo: appImages.user5,
      },
      {
        name: 'Jhon',
        userType: 'Photographer',
        gender: 'Female',
        age: '25',
        rating: 3,
        photo: appImages.user6,
      },
    ],
  },
];

export const ModelsDetails = [
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user1,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user2,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Female',
    age: '25',
    rating: 3,
    photo: appImages.user3,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user4,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user5,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Female',
    age: '25',
    rating: 3,
    photo: appImages.user6,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user8,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user7,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Female',
    age: '25',
    rating: 3,
    photo: appImages.user3,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user2,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user7,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Female',
    age: '25',
    rating: 3,
    photo: appImages.user5,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user3,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Male',
    age: '30',
    rating: 4,
    photo: appImages.user7,
  },
  {
    name: 'Jhon',
    userType: 'Photographer',
    gender: 'Female',
    age: '25',
    rating: 3,
    photo: appImages.user2,
  },
];
