import React from 'react';
import {StyleSheet} from 'react-native';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';
import {colors} from '../../../globals/utilities/colors';
import {fontSize} from '../../../globals/utilities/size';
import {fontFamily} from '../../../globals/utilities/fonts';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  Heading: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsBold,
    fontSize: fontSize.large,
    // marginTop: responsiveHeight(1),
    // marginLeft: responsiveWidth(5),
  },
  MainView: {
    width: responsiveWidth(90),
    alignSelf: 'center',
    marginTop: responsiveHeight(1),
    backgroundColor: colors.white,
    borderRadius: responsiveWidth(3),
    paddingVertical: responsiveHeight(4),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,

    elevation: 8,
    marginBottom: responsiveHeight(3),
    alignItems: 'center',
  },
  title: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsMedium,
    fontSize: fontSize.medium,
  },
  rightItems: {
    width: responsiveWidth(50),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tabsView: {
    width: responsiveWidth(100),
    paddingHorizontal: responsiveWidth(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: responsiveHeight(2.5),
  },
  active: {
    color: colors.yellow,
    fontFamily: fontFamily.MonstserratRegular,
    borderBottomWidth: responsiveWidth(1),
    borderBottomColor: colors.yellow,
    paddingBottom: responsiveHeight(1.5),
    fontSize: fontSize.medium,
  },
  inactive: {
    color: colors.lightText,
    fontFamily: fontFamily.MonstserratRegular,
    paddingBottom: responsiveHeight(1.5),
    fontSize: fontSize.medium,
    borderBottomWidth: responsiveWidth(1),
    borderBottomColor: colors.white,
  },
  //   rowView: {
  //     height: responsiveHeight(12),
  //     width: responsiveWidth(100),
  //     paddingHorizontal: responsiveWidth(8),
  //     flexDirection: 'row',
  //     alignItems: 'center',
  //     justifyContent: 'space-between',
  //     borderTopWidth: responsiveWidth(0.3),
  //     borderBottomWidth: responsiveWidth(0.3),
  //     borderColor: colors.lightText,
  //   },
  mediumText: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsSemiBold,
    fontSize: fontSize.medium,
    marginVertical: responsiveHeight(0.5),
  },
  price: {
    color: colors.yellow,
    fontFamily: fontFamily.PoppinsSemiBold,
    fontSize: fontSize.h5,
  },
  descriptionText: {
    width: responsiveWidth(84),
    alignSelf: 'center',
    color: colors.black,
    fontFamily: fontFamily.PoppinsSemiBold,
    fontSize: fontSize.regular,
    marginTop: responsiveHeight(2),
  },
  heading: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsSemiBold,
    fontSize: fontSize.large,
    marginLeft: responsiveWidth(5),
    marginTop: responsiveHeight(3),
    marginBottom: responsiveHeight(2),
  },
  ImageView: {
    width: responsiveWidth(90),
    alignSelf: 'center',
  },
  grayView: {
    height: responsiveHeight(25),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.darkGray,
  },
  addImageText: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsMedium,
    marginTop: responsiveHeight(0.5),
    fontSize: fontSize.medium,
  },
  image: {
    height: responsiveHeight(25),
    width: responsiveWidth(90),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: responsiveWidth(3),
  },
  tabsView: {
    width: responsiveWidth(100),
    paddingHorizontal: responsiveWidth(8),
    // height: responsiveHeight(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: responsiveHeight(2.5),
  },
  active: {
    color: colors.yellow,
    fontFamily: fontFamily.MonstserratRegular,
    borderBottomWidth: responsiveWidth(1),
    borderBottomColor: colors.yellow,
    paddingBottom: responsiveHeight(1.5),
    fontSize: fontSize.medium,
  },
  inactive: {
    color: colors.lightText,
    fontFamily: fontFamily.MonstserratRegular,
    paddingBottom: responsiveHeight(1.5),
    fontSize: fontSize.medium,
    borderBottomWidth: responsiveWidth(1),
    borderBottomColor: colors.white,
  },
  titleView: {
    height: responsiveHeight(8),
    borderTopWidth: responsiveWidth(0.3),
    borderBottomWidth: responsiveWidth(0.3),
    borderColor: colors.lightText,
    paddingLeft: responsiveWidth(8),
    justifyContent: 'center',
    marginBottom: responsiveHeight(1.5),
  },
  title: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsBold,
    fontSize: fontSize.large,
  },
  rowView: {
    width: responsiveWidth(84),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: responsiveHeight(1),
  },
  counterBox: {
    borderWidth: responsiveWidth(0.3),
    borderColor: colors.black,
    paddingHorizontal: responsiveWidth(1),
    paddingVertical: responsiveHeight(0.5),
    borderRadius: responsiveWidth(1),
    flexDirection: 'row',
    alignItems: 'center',
  },
  triangleIcon: {
    height: responsiveFontSize(1.5),
    width: responsiveFontSize(1.5),
    resizeMode: 'contain',
  },
  textView: {
    width: responsiveWidth(12),
    alignItems: 'center',
  },
  valueText: {
    color: colors.lightText,
    fontSize: responsiveFontSize(1.8),
  },
  boldText: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsSemiBold,
    fontSize: fontSize.medium,
  },
  line: {
    width: responsiveWidth(100),
    height: responsiveWidth(0.3),
    backgroundColor: colors.lightText,
    marginVertical: responsiveHeight(2),
  },
  finalText: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsMedium,
    marginLeft: responsiveWidth(8),
    marginBottom: responsiveHeight(2),
  },
  nextBtn: {
    height: responsiveHeight(8),
    width: responsiveWidth(24),
    backgroundColor: colors.black,
    alignItems: 'center',
    justifyContent: 'center',
    // position: 'absolute',
    // right: responsiveWidth(12),
    // bottom: responsiveHeight(10),
    borderRadius: responsiveWidth(10),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,

    elevation: 10,
    marginVertical: responsiveHeight(4),
    alignSelf: 'flex-end',
    marginRight: responsiveWidth(5),
  },
  greaterThan: {
    height: responsiveHeight(3),
    width: responsiveWidth(6),
    resizeMode: 'contain',
  },
  arrowBtn: {
    height: responsiveFontSize(4),
    width: responsiveFontSize(4),
    resizeMode: 'contain',
  },
  rrowview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn: {
    width: responsiveWidth(70),
    marginTop: responsiveHeight(15),
  },
  mediumHeading: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsMedium,
    marginLeft: responsiveWidth(8),
    fontSize: fontSize.medium,
  },
  descriptionInput: {
    backgroundColor: colors.grayBackground,
    alignSelf: 'center',
    width: responsiveWidth(84),
    borderRadius: responsiveWidth(3),
    // paddingHorizontal: responsiveWidth(3),
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Platform.OS === 'ios' ? responsiveHeight(1) : 0,
    paddingHorizontal:
      Platform.OS === 'ios' ? responsiveWidth(2) : responsiveWidth(1),
  },
});
