import React from 'react';
import {Platform, StyleSheet} from 'react-native';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';
import {colors} from '../../../../globals/utilities/colors';
import {fontSize} from '../../../../globals/utilities/size';
import {fontFamily} from '../../../../globals/utilities/fonts';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  heading: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsSemiBold,
    fontSize: fontSize.large,
    marginLeft: responsiveWidth(5),
    marginTop: responsiveHeight(3),
    marginBottom: responsiveHeight(1.5),
  },
  nextBtn: {
    height: responsiveHeight(8),
    width: responsiveWidth(24),
    backgroundColor: colors.black,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: responsiveWidth(10),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.34,
    shadowRadius: 6.27,

    elevation: 10,
    alignSelf: 'flex-end',
    marginRight: responsiveWidth(8),
    marginVertical: responsiveHeight(3),
  },
  greaterThan: {
    height: responsiveHeight(3),
    width: responsiveWidth(6),
    resizeMode: 'contain',
  },
  mediumHeading: {
    color: colors.black,
    fontFamily: fontFamily.PoppinsMedium,
    marginLeft: responsiveWidth(8),
    fontSize: fontSize.medium,
  },
  descriptionInput: {
    backgroundColor: colors.grayBackground,
    alignSelf: 'center',
    width: responsiveWidth(84),
    borderRadius: responsiveWidth(3),
    // paddingHorizontal: responsiveWidth(3),
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Platform.OS === 'ios' ? responsiveHeight(1) : 0,
    paddingHorizontal:
      Platform.OS === 'ios' ? responsiveWidth(2) : responsiveWidth(1),
  },
  inputIOS: {
    fontSize: responsiveFontSize(1.7),
    color: colors.black,
    height: responsiveHeight(7),
    width: responsiveWidth(74),
    alignSelf: 'center',
    marginTop: responsiveHeight(0.5),
    marginLeft: responsiveWidth(3),
    fontFamily: fontFamily.PoppinsMedium,
  },
  inputIOS1: {
    fontSize: responsiveFontSize(1.7),
    color: colors.black,
    height: responsiveHeight(7),
    width: responsiveWidth(74),
    alignSelf: 'center',
    marginTop: responsiveHeight(0.5),
    marginLeft: responsiveWidth(1),
    fontFamily: fontFamily.PoppinsMedium,
  },
  inputAndroid: {
    fontSize: responsiveFontSize(1.7),
    color: colors.black,
    height: responsiveHeight(7),
    width: responsiveWidth(74),
    alignSelf: 'center',
    marginTop: responsiveHeight(0.5),
    marginLeft: responsiveWidth(3),
    fontFamily: fontFamily.PoppinsMedium,
  },
  inputAndroid1: {
    fontSize: responsiveFontSize(1.7),
    color: colors.black,
    height: responsiveHeight(7),
    width: responsiveWidth(74),
    alignSelf: 'center',
    marginTop: responsiveHeight(0.5),
    marginLeft: responsiveWidth(1),
    fontFamily: fontFamily.PoppinsMedium,
  },
  pickerView: {
    backgroundColor: colors.grayBackground,
    alignSelf: 'center',
    width: responsiveWidth(84),
    height: responsiveHeight(8),
    // borderWidth: responsiveWidth(0.1),
    // borderColor: textColor.inputBorder,
    borderRadius: responsiveWidth(3),
    justifyContent: 'space-between',
    paddingHorizontal: responsiveWidth(1),
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: responsiveHeight(4),
  },
  checkBtn: {
    borderWidth: responsiveWidth(0.3),
    height: responsiveWidth(6),
    width: responsiveWidth(6),
    borderRadius: responsiveWidth(3),
    borderColor: colors.grayBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkedBtn: {
    backgroundColor: colors.yellow,
    height: responsiveWidth(4),
    width: responsiveWidth(4),
    borderRadius: responsiveWidth(2),
    marginBottom: Platform.OS === 'android' ? 0 : responsiveHeight(0.05),
  },
  flBtnView: {
    width: responsiveWidth(40),
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: responsiveHeight(1.5),
  },
  checkBtnText: {
    marginLeft: responsiveWidth(2),
    fontFamily: fontFamily.PoppinsSemiBold,
    marginTop: responsiveHeight(0.5),
    color: colors.black,
    fontSize: fontSize.small,
  },
  rowView: {
    width: responsiveWidth(84),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Modalbackground: {
    backgroundColor: colors.white,
    height: responsiveHeight(30),
    width: responsiveWidth(90),
    justifyContent: 'center',
    borderRadius: responsiveWidth(3),
  },
  modalWrapper: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  genderText: {
    color: colors.black,
    marginLeft: responsiveWidth(4),
    fontFamily: fontFamily.PoppinsMedium,
  },
  DoneText: {
    color: colors.white,
    fontFamily: fontFamily.PoppinsBold,
    alignSelf: 'center',
    fontSize: fontSize.large,
  },
  DoneBtn: {
    backgroundColor: colors.black,
    width: responsiveWidth(30),
    alignSelf: 'center',
    marginTop: responsiveHeight(3),
    height: responsiveHeight(6),
    justifyContent: 'center',
    borderRadius: responsiveWidth(3),
  },
});
